/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */

/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_API_URL: string;
  readonly VITE_RECAPTCHA_SITE_KEY: string;
  readonly VITE_GA_MEASUREMENT_ID: string;
}
interface ImportMeta {
  readonly env: ImportMetaEnv;
}
